resilience4j:
  circuitbreaker:
    instances:
      authenticationService:
        failure-rate-threshold: 50
        minimum-number-of-calls: 3
        sliding-window-size: 3
        sliding-window-type: count-based
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-state: true
application:
  security:
    jwt:
      secret-key: 404E6352665564586E3272357538782F413F4428472848625064536756685970
      expiration: 86400000 # a day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds